// frontend/src/components/Step1GraphBuild.vue
<template>
  <div class="workbench-panel">
    <div class="scroll-container">
      <!-- Step 01: Ontology -->
      <div class="step-card" :class="{ 'active': currentPhase === 0, 'completed': currentPhase > 0 }">
        <div class="card-header">
          <div class="step-info">
            <span class="step-num">01</span>
            <span class="step-title">Ontology Generation</span>
          </div>
          <div class="step-status">
            <span v-if="currentPhase > 0" class="badge success">Completed</span>
            <span v-else-if="currentPhase === 0" class="badge processing">Generating</span>
            <span v-else class="badge pending">Waiting</span>
          </div>
        </div>
        
        <div class="card-content">
          <p class="api-note">POST /api/graph/ontology/generate</p>
          <p class="description">
            LLM analyzes document content and simulation requirements, extracts reality seeds, and auto-generates a suitable ontology structure
          </p>

          <!-- Loading / Progress -->
          <div v-if="currentPhase === 0 && ontologyProgress" class="progress-section">
            <div class="spinner-sm"></div>
            <span>{{ ontologyProgress.message || 'Analyzing documents...' }}</span>
          </div>

          <!-- Detail Overlay -->
          <div v-if="selectedOntologyItem" class="ontology-detail-overlay">
            <div class="detail-header">
               <div class="detail-title-group">
                  <span class="detail-type-badge">{{ selectedOntologyItem.itemType === 'entity' ? 'ENTITY' : 'RELATION' }}</span>
                  <span class="detail-name">{{ selectedOntologyItem.name }}</span>
               </div>
               <button class="close-btn" @click="selectedOntologyItem = null">×</button>
            </div>
            <div class="detail-body">
               <div class="detail-desc">{{ selectedOntologyItem.description }}</div>
               
               <!-- Attributes -->
               <div class="detail-section" v-if="selectedOntologyItem.attributes?.length">
                  <span class="section-label">ATTRIBUTES</span>
                  <div class="attr-list">
                     <div v-for="attr in selectedOntologyItem.attributes" :key="attr.name" class="attr-item">
                        <span class="attr-name">{{ attr.name }}</span>
                        <span class="attr-type">({{ attr.type }})</span>
                        <span class="attr-desc">{{ attr.description }}</span>
                     </div>
                  </div>
               </div>

               <!-- Examples (Entity) -->
               <div class="detail-section" v-if="selectedOntologyItem.examples?.length">
                  <span class="section-label">EXAMPLES</span>
                  <div class="example-list">
                     <span v-for="ex in selectedOntologyItem.examples" :key="ex" class="example-tag">{{ ex }}</span>
                  </div>
               </div>

               <!-- Source/Target (Relation) -->
               <div class="detail-section" v-if="selectedOntologyItem.source_targets?.length">
                  <span class="section-label">CONNECTIONS</span>
                  <div class="conn-list">
                     <div v-for="(conn, idx) in selectedOntologyItem.source_targets" :key="idx" class="conn-item">
                        <span class="conn-node">{{ conn.source }}</span>
                        <span class="conn-arrow">→</span>
                        <span class="conn-node">{{ conn.target }}</span>
                     </div>
                  </div>
               </div>
            </div>
          </div>

          <!-- Generated Entity Tags -->
          <div v-if="projectData?.ontology?.entity_types" class="tags-container" :class="{ 'dimmed': selectedOntologyItem }">
            <span class="tag-label">GENERATED ENTITY TYPES</span>
            <div class="tags-list">
              <span 
                v-for="entity in projectData.ontology.entity_types" 
                :key="entity.name" 
                class="entity-tag clickable"
                @click="selectOntologyItem(entity, 'entity')"
              >
                {{ entity.name }}
              </span>
            </div>
          </div>

          <!-- Generated Relation Tags -->
          <div v-if="projectData?.ontology?.edge_types" class="tags-container" :class="{ 'dimmed': selectedOntologyItem }">
            <span class="tag-label">GENERATED RELATION TYPES</span>
            <div class="tags-list">
              <span 
                v-for="rel in projectData.ontology.edge_types" 
                :key="rel.name" 
                class="entity-tag clickable"
                @click="selectOntologyItem(rel, 'relation')"
              >
                {{ rel.name }}
              </span>
            </div>
          </div>
        </div>
      </div>

      <!-- Step 02: Graph Build -->
      <div class="step-card" :class="{ 'active': currentPhase === 1, 'completed': currentPhase > 1 }">
        <div class="card-header">
          <div class="step-info">
            <span class="step-num">02</span>
            <span class="step-title">GraphRAG Building</span>
          </div>
          <div class="step-status">
            <span v-if="currentPhase > 1" class="badge success">Completed</span>
            <span v-else-if="currentPhase === 1" class="badge processing">{{ buildProgress?.progress || 0 }}%</span>
            <span v-else class="badge pending">Waiting</span>
          </div>
        </div>

        <div class="card-content">
          <p class="api-note">POST /api/graph/build</p>
          <p class="description">
            Based on the generated ontology, automatically chunks documents and calls Zep to build a knowledge graph, extracting entities and relationships while forming temporal memory and community summaries
          </p>
          
          <!-- Stats Cards -->
          <div class="stats-grid">
            <div class="stat-card">
              <span class="stat-value">{{ graphStats.nodes }}</span>
              <span class="stat-label">Entity Nodes</span>
            </div>
            <div class="stat-card">
              <span class="stat-value">{{ graphStats.edges }}</span>
              <span class="stat-label">Relationship Edges</span>
            </div>
            <div class="stat-card">
              <span class="stat-value">{{ graphStats.types }}</span>
              <span class="stat-label">Schema Types</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Step 03: Complete -->
      <div class="step-card" :class="{ 'active': currentPhase === 2, 'completed': currentPhase >= 2 }">
        <div class="card-header">
          <div class="step-info">
            <span class="step-num">03</span>
            <span class="step-title">Build Complete</span>
          </div>
          <div class="step-status">
            <span v-if="currentPhase >= 2" class="badge accent">In Progress</span>
          </div>
        </div>
        
        <div class="card-content">
          <p class="api-note">POST /api/simulation/create</p>
          <p class="description">Graph building is complete. Proceed to the next step for simulation environment setup.</p>
          <button
            class="action-btn"
            :disabled="currentPhase < 2 || creatingSimulation"
            @click="handleEnterEnvSetup"
          >
            <span v-if="creatingSimulation" class="spinner-sm"></span>
            {{ creatingSimulation ? 'Creating...' : 'Enter Environment Setup ➝' }}
          </button>
        </div>
      </div>
    </div>

    <!-- Bottom Info / Logs -->
    <div class="system-logs">
      <div class="log-header">
        <span class="log-title">SYSTEM DASHBOARD</span>
        <span class="log-id">{{ projectData?.project_id || 'NO_PROJECT' }}</span>
      </div>
      <div class="log-content" ref="logContent">
        <div class="log-line" v-for="(log, idx) in systemLogs" :key="idx">
          <span class="log-time">{{ log.time }}</span>
          <span class="log-msg">{{ log.msg }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, ref, watch, nextTick } from 'vue'
import { useRouter } from 'vue-router'
import { createSimulation } from '../api/simulation'

const router = useRouter()

const props = defineProps({
  currentPhase: { type: Number, default: 0 },
  projectData: Object,
  ontologyProgress: Object,
  buildProgress: Object,
  graphData: Object,
  systemLogs: { type: Array, default: () => [] }
})

defineEmits(['next-step'])

const selectedOntologyItem = ref(null)
const logContent = ref(null)
const creatingSimulation = ref(false)

// Enter environment setup - create simulation and navigate
const handleEnterEnvSetup = async () => {
  if (!props.projectData?.project_id || !props.projectData?.graph_id) {
    console.error('Missing project or graph information')
    return
  }
  
  creatingSimulation.value = true
  
  try {
    const res = await createSimulation({
      project_id: props.projectData.project_id,
      graph_id: props.projectData.graph_id,
      enable_twitter: true,
      enable_reddit: true
    })
    
    if (res.success && res.data?.simulation_id) {
      // Navigate to simulation page
      router.push({
        name: 'Simulation',
        params: { simulationId: res.data.simulation_id }
      })
    } else {
      console.error('Failed to create simulation:', res.error)
      alert('Failed to create simulation: ' + (res.error || 'Unknown error'))
    }
  } catch (err) {
    console.error('Simulation creation error:', err)
    alert('Simulation creation error: ' + err.message)
  } finally {
    creatingSimulation.value = false
  }
}

const selectOntologyItem = (item, type) => {
  selectedOntologyItem.value = { ...item, itemType: type }
}

const graphStats = computed(() => {
  const nodes = props.graphData?.node_count || props.graphData?.nodes?.length || 0
  const edges = props.graphData?.edge_count || props.graphData?.edges?.length || 0
  const types = props.projectData?.ontology?.entity_types?.length || 0
  return { nodes, edges, types }
})

const formatDate = (dateStr) => {
  if (!dateStr) return '--:--:--'
  const d = new Date(dateStr)
  return d.toLocaleTimeString('en-US', { hour12: false }) + '.' + d.getMilliseconds()
}

// Auto-scroll logs
watch(() => props.systemLogs.length, () => {
  nextTick(() => {
    if (logContent.value) {
      logContent.value.scrollTop = logContent.value.scrollHeight
    }
  })
})
</script>

<style scoped>
.workbench-panel {
  height: 100%;
  background-color: #FAFAFA;
  display: flex;
  flex-direction: column;
  position: relative;
  overflow: hidden;
}

.scroll-container {
  flex: 1;
  overflow-y: auto;
  padding: 24px;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.step-card {
  background: #FFF;
  border-radius: 8px;
  padding: 20px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.04);
  border: 1px solid #EAEAEA;
  transition: all 0.3s ease;
  position: relative; /* For absolute overlay */
}

.step-card.active {
  border-color: #FF5722;
  box-shadow: 0 4px 12px rgba(255, 87, 34, 0.08);
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.step-info {
  display: flex;
  align-items: center;
  gap: 12px;
}

.step-num {
  font-family: 'JetBrains Mono', monospace;
  font-size: 20px;
  font-weight: 700;
  color: #E0E0E0;
}

.step-card.active .step-num,
.step-card.completed .step-num {
  color: #000;
}

.step-title {
  font-weight: 600;
  font-size: 14px;
  letter-spacing: 0.5px;
}

.badge {
  font-size: 10px;
  padding: 4px 8px;
  border-radius: 4px;
  font-weight: 600;
  text-transform: uppercase;
}

.badge.success { background: #E8F5E9; color: #2E7D32; }
.badge.processing { background: #FF5722; color: #FFF; }
.badge.accent { background: #FF5722; color: #FFF; }
.badge.pending { background: #F5F5F5; color: #999; }

.api-note {
  font-family: 'JetBrains Mono', monospace;
  font-size: 10px;
  color: #999;
  margin-bottom: 8px;
}

.description {
  font-size: 12px;
  color: #666;
  line-height: 1.5;
  margin-bottom: 16px;
}

/* Step 01 Tags */
.tags-container {
  margin-top: 12px;
  transition: opacity 0.3s;
}

.tags-container.dimmed {
    opacity: 0.3;
    pointer-events: none;
}

.tag-label {
  display: block;
  font-size: 10px;
  color: #AAA;
  margin-bottom: 8px;
  font-weight: 600;
}

.tags-list {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.entity-tag {
  background: #F5F5F5;
  border: 1px solid #EEE;
  padding: 4px 10px;
  border-radius: 4px;
  font-size: 11px;
  color: #333;
  font-family: 'JetBrains Mono', monospace;
  transition: all 0.2s;
}

.entity-tag.clickable {
    cursor: pointer;
}

.entity-tag.clickable:hover {
    background: #E0E0E0;
    border-color: #CCC;
}

/* Ontology Detail Overlay */
.ontology-detail-overlay {
    position: absolute;
    top: 60px; /* Below header roughly */
    left: 20px;
    right: 20px;
    bottom: 20px;
    background: rgba(255, 255, 255, 0.98);
    backdrop-filter: blur(4px);
    z-index: 10;
    border: 1px solid #EAEAEA;
    box-shadow: 0 4px 20px rgba(0,0,0,0.05);
    border-radius: 6px;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    animation: fadeIn 0.2s ease-out;
}

@keyframes fadeIn { from { opacity: 0; transform: translateY(5px); } to { opacity: 1; transform: translateY(0); } }

.detail-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 12px 16px;
    border-bottom: 1px solid #EAEAEA;
    background: #FAFAFA;
}

.detail-title-group {
    display: flex;
    align-items: center;
    gap: 8px;
}

.detail-type-badge {
    font-size: 9px;
    font-weight: 700;
    color: #FFF;
    background: #000;
    padding: 2px 6px;
    border-radius: 2px;
    text-transform: uppercase;
}

.detail-name {
    font-size: 14px;
    font-weight: 700;
    font-family: 'JetBrains Mono', monospace;
}

.close-btn {
    background: none;
    border: none;
    font-size: 18px;
    color: #999;
    cursor: pointer;
    line-height: 1;
}

.close-btn:hover {
    color: #333;
}

.detail-body {
    flex: 1;
    overflow-y: auto;
    padding: 16px;
}

.detail-desc {
    font-size: 12px;
    color: #444;
    line-height: 1.5;
    margin-bottom: 16px;
    padding-bottom: 12px;
    border-bottom: 1px dashed #EAEAEA;
}

.detail-section {
    margin-bottom: 16px;
}

.section-label {
    display: block;
    font-size: 10px;
    font-weight: 600;
    color: #AAA;
    margin-bottom: 8px;
}

.attr-list, .conn-list {
    display: flex;
    flex-direction: column;
    gap: 6px;
}

.attr-item {
    font-size: 11px;
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    align-items: baseline;
    padding: 4px;
    background: #F9F9F9;
    border-radius: 4px;
}

.attr-name {
    font-family: 'JetBrains Mono', monospace;
    font-weight: 600;
    color: #000;
}

.attr-type {
    color: #999;
    font-size: 10px;
}

.attr-desc {
    color: #555;
    flex: 1;
    min-width: 150px;
}

.example-list {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
}

.example-tag {
    font-size: 11px;
    background: #FFF;
    border: 1px solid #E0E0E0;
    padding: 3px 8px;
    border-radius: 12px;
    color: #555;
}

.conn-item {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 11px;
    padding: 6px;
    background: #F5F5F5;
    border-radius: 4px;
    font-family: 'JetBrains Mono', monospace;
}

.conn-node {
    font-weight: 600;
    color: #333;
}

.conn-arrow {
    color: #BBB;
}

/* Step 02 Stats */
.stats-grid {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 12px;
  background: #F9F9F9;
  padding: 16px;
  border-radius: 6px;
}

.stat-card {
  text-align: center;
}

.stat-value {
  display: block;
  font-size: 20px;
  font-weight: 700;
  color: #000;
  font-family: 'JetBrains Mono', monospace;
}

.stat-label {
  font-size: 9px;
  color: #999;
  text-transform: uppercase;
  margin-top: 4px;
  display: block;
}

/* Step 03 Button */
.action-btn {
  width: 100%;
  background: #000;
  color: #FFF;
  border: none;
  padding: 14px;
  border-radius: 4px;
  font-size: 12px;
  font-weight: 600;
  cursor: pointer;
  transition: opacity 0.2s;
}

.action-btn:hover:not(:disabled) {
  opacity: 0.8;
}

.action-btn:disabled {
  background: #CCC;
  cursor: not-allowed;
}

.progress-section {
  display: flex;
  align-items: center;
  gap: 10px;
  font-size: 12px;
  color: #FF5722;
  margin-bottom: 12px;
}

.spinner-sm {
  width: 14px;
  height: 14px;
  border: 2px solid #FFCCBC;
  border-top-color: #FF5722;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin { to { transform: rotate(360deg); } }

/* System Logs */
.system-logs {
  background: #000;
  color: #DDD;
  padding: 16px;
  font-family: 'JetBrains Mono', monospace;
  border-top: 1px solid #222;
  flex-shrink: 0;
}

.log-header {
  display: flex;
  justify-content: space-between;
  border-bottom: 1px solid #333;
  padding-bottom: 8px;
  margin-bottom: 8px;
  font-size: 10px;
  color: #888;
}

.log-content {
  display: flex;
  flex-direction: column;
  gap: 4px;
  height: 80px; /* Approx 4 lines visible */
  overflow-y: auto;
  padding-right: 4px;
}

.log-content::-webkit-scrollbar {
  width: 4px;
}

.log-content::-webkit-scrollbar-thumb {
  background: #333;
  border-radius: 2px;
}

.log-line {
  font-size: 11px;
  display: flex;
  gap: 12px;
  line-height: 1.5;
}

.log-time {
  color: #666;
  min-width: 75px;
}

.log-msg {
  color: #CCC;
  word-break: break-all;
}
</style>

// frontend-react/src/components/wizard/step-1-graph-build.tsx
import { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { createSimulation } from '@/api/simulation';
import type { LogEntry } from '@/components/shared/log-viewer';
import { cx } from '@/utils/cx';

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface OntologyAttribute {
  name: string;
  type?: string;
  description?: string;
}

interface OntologyEntityType {
  name: string;
  description?: string;
  attributes?: OntologyAttribute[];
  examples?: string[];
  [key: string]: unknown;
}

interface OntologyEdgeType {
  name: string;
  description?: string;
  attributes?: OntologyAttribute[];
  source_targets?: { source: string; target: string }[];
  [key: string]: unknown;
}

interface SelectedItem {
  name: string;
  description?: string;
  itemType: 'entity' | 'relation';
  attributes?: OntologyAttribute[];
  examples?: string[];
  source_targets?: { source: string; target: string }[];
  [key: string]: unknown;
}

interface Step1Props {
  currentPhase: number;
  projectData: {
    project_id: string;
    graph_id?: string;
    ontology?: {
      entity_types?: OntologyEntityType[];
      edge_types?: OntologyEdgeType[];
      relation_types?: OntologyEdgeType[];
    };
  } | null;
  ontologyProgress: { message: string } | null;
  buildProgress: { progress: number; message?: string } | null;
  graphData: {
    node_count?: number;
    edge_count?: number;
    nodes?: unknown[];
    edges?: unknown[];
  } | null;
  systemLogs: LogEntry[];
  onNextStep?: () => void;
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

function Badge({ status }: { status: 'completed' | 'processing' | 'pending' | 'accent'; label: string }) {
  return null; // rendered inline below for flexibility
}

function StepBadge({
  phase,
  stepIndex,
  progressLabel,
}: {
  phase: number;
  stepIndex: number;
  progressLabel?: string;
}) {
  if (phase > stepIndex) {
    return (
      <span className="rounded bg-green-50 px-2 py-1 text-[10px] font-semibold uppercase text-green-700">
        Completed
      </span>
    );
  }
  if (phase === stepIndex) {
    return (
      <span className="rounded bg-brand-600 px-2 py-1 text-[10px] font-semibold uppercase text-white">
        {progressLabel ?? 'Processing'}
      </span>
    );
  }
  return (
    <span className="rounded bg-neutral-100 px-2 py-1 text-[10px] font-semibold uppercase text-neutral-400">
      Pending
    </span>
  );
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function Step1GraphBuild({
  currentPhase,
  projectData,
  ontologyProgress,
  buildProgress,
  graphData,
  systemLogs,
}: Step1Props) {
  const navigate = useNavigate();
  const [creatingSimulation, setCreatingSimulation] = useState(false);
  const [selectedOntologyItem, setSelectedOntologyItem] = useState<SelectedItem | null>(null);
  const logContentRef = useRef<HTMLDivElement>(null);

  /* Auto-scroll logs */
  useEffect(() => {
    if (logContentRef.current) {
      logContentRef.current.scrollTop = logContentRef.current.scrollHeight;
    }
  }, [systemLogs.length]);

  /* Graph stats (derived) */
  const graphStats = {
    nodes: graphData?.node_count || graphData?.nodes?.length || 0,
    edges: graphData?.edge_count || graphData?.edges?.length || 0,
    types: projectData?.ontology?.entity_types?.length || 0,
  };

  /* Create simulation and navigate */
  const handleEnterEnvSetup = async () => {
    if (!projectData?.project_id || !projectData?.graph_id) {
      console.error('Missing project or graph information');
      return;
    }

    setCreatingSimulation(true);

    try {
      const res = await createSimulation({
        project_id: projectData.project_id,
        graph_id: projectData.graph_id,
        enable_twitter: true,
        enable_reddit: true,
      });

      if (res.success && res.data?.simulation_id) {
        navigate(`/simulation/${res.data.simulation_id}`);
      } else {
        console.error('Failed to create simulation:', res.error);
        alert('Failed to create simulation: ' + (res.error || 'Unknown error'));
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      console.error('Error creating simulation:', err);
      alert('Error creating simulation: ' + message);
    } finally {
      setCreatingSimulation(false);
    }
  };

  const selectOntologyItem = (item: OntologyEntityType | OntologyEdgeType, type: 'entity' | 'relation') => {
    setSelectedOntologyItem({ ...item, itemType: type } as SelectedItem);
  };

  /* ---------------------------------------------------------------- */
  /*  Render                                                           */
  /* ---------------------------------------------------------------- */

  return (
    <div className="flex h-full flex-col overflow-hidden bg-neutral-50">
      {/* Scrollable step cards */}
      <div className="flex flex-1 flex-col gap-5 overflow-y-auto p-6">
        {/* ============================================================ */}
        {/* Step 01 - Ontology Generation                                */}
        {/* ============================================================ */}
        <div
          className={cx(
            'relative rounded-lg border bg-white p-5 shadow-sm transition-all',
            currentPhase === 0 && 'border-brand-600 shadow-md shadow-brand-600/[.08]',
            currentPhase > 0 && 'border-neutral-200',
            currentPhase < 0 && 'border-neutral-200',
          )}
        >
          {/* Header */}
          <div className="mb-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span
                className={cx(
                  'font-mono text-xl font-bold',
                  currentPhase >= 0 ? 'text-neutral-900' : 'text-neutral-300',
                )}
              >
                01
              </span>
              <span className="text-sm font-semibold tracking-wide">Ontology Generation</span>
            </div>
            <StepBadge phase={currentPhase} stepIndex={0} progressLabel="Generating" />
          </div>

          {/* Card content */}
          <div>
            <p className="mb-2 font-mono text-[10px] text-neutral-400">
              POST /api/graph/ontology/generate
            </p>
            <p className="mb-4 text-xs leading-relaxed text-neutral-500">
              LLM analyses document content and simulation requirements to extract real seeds and
              automatically generate an appropriate ontology structure.
            </p>

            {/* Progress spinner */}
            {currentPhase === 0 && ontologyProgress && (
              <div className="mb-3 flex items-center gap-2.5 text-xs text-brand-600">
                <div className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-brand-200 border-t-brand-600" />
                <span>{ontologyProgress.message || 'Analysing documents...'}</span>
              </div>
            )}

            {/* Detail overlay */}
            {selectedOntologyItem && (
              <div className="absolute inset-x-5 bottom-5 top-[60px] z-10 flex animate-in fade-in slide-in-from-bottom-1 flex-col overflow-hidden rounded-md border border-neutral-200 bg-white/[.98] shadow-lg backdrop-blur-sm">
                {/* Overlay header */}
                <div className="flex items-center justify-between border-b border-neutral-200 bg-neutral-50 px-4 py-3">
                  <div className="flex items-center gap-2">
                    <span className="rounded-sm bg-neutral-900 px-1.5 py-0.5 text-[9px] font-bold uppercase text-white">
                      {selectedOntologyItem.itemType === 'entity' ? 'Entity' : 'Relation'}
                    </span>
                    <span className="font-mono text-sm font-bold">{selectedOntologyItem.name}</span>
                  </div>
                  <button
                    onClick={() => setSelectedOntologyItem(null)}
                    className="text-lg leading-none text-neutral-400 hover:text-neutral-700"
                  >
                    &times;
                  </button>
                </div>

                {/* Overlay body */}
                <div className="flex-1 overflow-y-auto p-4">
                  {selectedOntologyItem.description && (
                    <p className="mb-4 border-b border-dashed border-neutral-200 pb-3 text-xs leading-relaxed text-neutral-600">
                      {selectedOntologyItem.description}
                    </p>
                  )}

                  {/* Attributes */}
                  {selectedOntologyItem.attributes && selectedOntologyItem.attributes.length > 0 && (
                    <div className="mb-4">
                      <span className="mb-2 block text-[10px] font-semibold text-neutral-400">
                        ATTRIBUTES
                      </span>
                      <div className="flex flex-col gap-1.5">
                        {selectedOntologyItem.attributes.map((attr) => (
                          <div
                            key={attr.name}
                            className="flex flex-wrap items-baseline gap-1.5 rounded bg-neutral-50 p-1.5 text-[11px]"
                          >
                            <span className="font-mono font-semibold text-neutral-900">
                              {attr.name}
                            </span>
                            {attr.type && (
                              <span className="text-[10px] text-neutral-400">({attr.type})</span>
                            )}
                            {attr.description && (
                              <span className="min-w-[150px] flex-1 text-neutral-500">
                                {attr.description}
                              </span>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Examples (entity) */}
                  {selectedOntologyItem.examples && selectedOntologyItem.examples.length > 0 && (
                    <div className="mb-4">
                      <span className="mb-2 block text-[10px] font-semibold text-neutral-400">
                        EXAMPLES
                      </span>
                      <div className="flex flex-wrap gap-1.5">
                        {selectedOntologyItem.examples.map((ex) => (
                          <span
                            key={ex}
                            className="rounded-full border border-neutral-200 bg-white px-2 py-0.5 text-[11px] text-neutral-500"
                          >
                            {ex}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Connections (relation) */}
                  {selectedOntologyItem.source_targets &&
                    selectedOntologyItem.source_targets.length > 0 && (
                      <div className="mb-4">
                        <span className="mb-2 block text-[10px] font-semibold text-neutral-400">
                          CONNECTIONS
                        </span>
                        <div className="flex flex-col gap-1.5">
                          {selectedOntologyItem.source_targets.map((conn, idx) => (
                            <div
                              key={idx}
                              className="flex items-center gap-2 rounded bg-neutral-100 p-1.5 font-mono text-[11px]"
                            >
                              <span className="font-semibold text-neutral-700">{conn.source}</span>
                              <span className="text-neutral-300">{'->'}</span>
                              <span className="font-semibold text-neutral-700">{conn.target}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                </div>
              </div>
            )}

            {/* Entity type tags */}
            {projectData?.ontology?.entity_types && (
              <div
                className={cx(
                  'mt-3 transition-opacity',
                  selectedOntologyItem && 'pointer-events-none opacity-30',
                )}
              >
                <span className="mb-2 block text-[10px] font-semibold text-neutral-400">
                  GENERATED ENTITY TYPES
                </span>
                <div className="flex flex-wrap gap-2">
                  {projectData.ontology.entity_types.map((entity) => (
                    <button
                      key={entity.name}
                      onClick={() => selectOntologyItem(entity, 'entity')}
                      className="cursor-pointer rounded border border-neutral-200 bg-neutral-100 px-2.5 py-1 font-mono text-[11px] text-neutral-700 transition-colors hover:border-neutral-300 hover:bg-neutral-200"
                    >
                      {entity.name}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Relation / edge type tags */}
            {(projectData?.ontology?.edge_types || projectData?.ontology?.relation_types) && (
              <div
                className={cx(
                  'mt-3 transition-opacity',
                  selectedOntologyItem && 'pointer-events-none opacity-30',
                )}
              >
                <span className="mb-2 block text-[10px] font-semibold text-neutral-400">
                  GENERATED RELATION TYPES
                </span>
                <div className="flex flex-wrap gap-2">
                  {(projectData.ontology.edge_types || projectData.ontology.relation_types || []).map((rel) => (
                    <button
                      key={rel.name}
                      onClick={() => selectOntologyItem(rel, 'relation')}
                      className="cursor-pointer rounded border border-neutral-200 bg-neutral-100 px-2.5 py-1 font-mono text-[11px] text-neutral-700 transition-colors hover:border-neutral-300 hover:bg-neutral-200"
                    >
                      {rel.name}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* ============================================================ */}
        {/* Step 02 - GraphRAG Build                                     */}
        {/* ============================================================ */}
        <div
          className={cx(
            'rounded-lg border bg-white p-5 shadow-sm transition-all',
            currentPhase === 1 && 'border-brand-600 shadow-md shadow-brand-600/[.08]',
            currentPhase !== 1 && 'border-neutral-200',
          )}
        >
          {/* Header */}
          <div className="mb-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span
                className={cx(
                  'font-mono text-xl font-bold',
                  currentPhase >= 1 ? 'text-neutral-900' : 'text-neutral-300',
                )}
              >
                02
              </span>
              <span className="text-sm font-semibold tracking-wide">GraphRAG Build</span>
            </div>
            <StepBadge
              phase={currentPhase}
              stepIndex={1}
              progressLabel={`${buildProgress?.progress || 0}%`}
            />
          </div>

          <div>
            <p className="mb-2 font-mono text-[10px] text-neutral-400">POST /api/graph/build</p>
            <p className="mb-4 text-xs leading-relaxed text-neutral-500">
              Based on the generated ontology, documents are automatically chunked and Zep is called
              to build a knowledge graph, extract entities and relations, and form temporal memory
              with community summaries.
            </p>

            {/* Stats grid */}
            <div className="grid grid-cols-3 gap-3 rounded-md bg-neutral-50 p-4">
              <div className="text-center">
                <span className="block font-mono text-xl font-bold text-neutral-900">
                  {graphStats.nodes}
                </span>
                <span className="mt-1 block text-[9px] uppercase text-neutral-400">Nodes</span>
              </div>
              <div className="text-center">
                <span className="block font-mono text-xl font-bold text-neutral-900">
                  {graphStats.edges}
                </span>
                <span className="mt-1 block text-[9px] uppercase text-neutral-400">Edges</span>
              </div>
              <div className="text-center">
                <span className="block font-mono text-xl font-bold text-neutral-900">
                  {graphStats.types}
                </span>
                <span className="mt-1 block text-[9px] uppercase text-neutral-400">
                  Schema Types
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* ============================================================ */}
        {/* Step 03 - Build Complete                                      */}
        {/* ============================================================ */}
        <div
          className={cx(
            'rounded-lg border bg-white p-5 shadow-sm transition-all',
            currentPhase === 2 && 'border-brand-600 shadow-md shadow-brand-600/[.08]',
            currentPhase !== 2 && 'border-neutral-200',
          )}
        >
          {/* Header */}
          <div className="mb-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span
                className={cx(
                  'font-mono text-xl font-bold',
                  currentPhase >= 2 ? 'text-neutral-900' : 'text-neutral-300',
                )}
              >
                03
              </span>
              <span className="text-sm font-semibold tracking-wide">Build Complete</span>
            </div>
            {currentPhase >= 2 && (
              <span className="rounded bg-brand-600 px-2 py-1 text-[10px] font-semibold uppercase text-white">
                Ready
              </span>
            )}
          </div>

          <div>
            <p className="mb-2 font-mono text-[10px] text-neutral-400">
              POST /api/simulation/create
            </p>
            <p className="mb-4 text-xs leading-relaxed text-neutral-500">
              Graph construction is complete. Proceed to the next step to set up the simulation
              environment.
            </p>

            <button
              disabled={currentPhase < 2 || creatingSimulation}
              onClick={handleEnterEnvSetup}
              className={cx(
                'w-full rounded bg-neutral-900 px-4 py-3.5 text-xs font-semibold text-white transition-opacity',
                'hover:opacity-80',
                'disabled:cursor-not-allowed disabled:bg-neutral-300',
              )}
            >
              {creatingSimulation ? (
                <span className="inline-flex items-center gap-2">
                  <span className="inline-block h-3.5 w-3.5 animate-spin rounded-full border-2 border-neutral-400 border-t-white" />
                  Creating...
                </span>
              ) : (
                'Enter Environment Setup \u27B6'
              )}
            </button>
          </div>
        </div>
      </div>

      {/* ============================================================== */}
      {/* System Logs Dashboard                                           */}
      {/* ============================================================== */}
      <div className="shrink-0 border-t border-neutral-800 bg-neutral-950 p-4 font-mono text-neutral-300">
        <div className="mb-2 flex items-center justify-between border-b border-neutral-800 pb-2 text-[10px] text-neutral-500">
          <span>SYSTEM DASHBOARD</span>
          <span>{projectData?.project_id || 'NO_PROJECT'}</span>
        </div>
        <div
          ref={logContentRef}
          className="flex h-20 flex-col gap-1 overflow-y-auto pr-1 scrollbar-thin scrollbar-thumb-neutral-800"
        >
          {systemLogs.map((log, idx) => (
            <div key={idx} className="flex gap-3 text-[11px] leading-relaxed">
              <span className="shrink-0 text-neutral-600" style={{ minWidth: 75 }}>
                {log.timestamp}
              </span>
              <span className="break-all text-neutral-400">{log.message}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
