// frontend-react/src/pages/interaction-view.tsx
import { useState, useEffect, useCallback, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getReport } from '../api/report';
import { getSimulation } from '../api/simulation';
import { getProject, getGraphData } from '../api/graph';
import { GraphPanel } from '../components/graph-panel/graph-panel';
import { Step5Interaction } from '../components/wizard/step-5-interaction';
import { formatLogTimestamp, type LogEntry } from '../components/shared/log-viewer';
import type { GraphNode, GraphEdge } from '../api/types';
import { cx } from '../utils/cx';

type ViewMode = 'graph' | 'split' | 'workbench';

export function InteractionView() {
  const { reportId } = useParams<{ reportId: string }>();
  const navigate = useNavigate();

  const [viewMode, setViewMode] = useState<ViewMode>('workbench');
  const [graphData, setGraphData] = useState<{ nodes: GraphNode[]; edges: GraphEdge[]; node_count: number; edge_count: number } | null>(null);
  const [graphLoading, setGraphLoading] = useState(false);
  const [simulationId, setSimulationId] = useState('');
  const [systemLogs, setSystemLogs] = useState<LogEntry[]>([]);
  const [currentStatus, setCurrentStatus] = useState('ready');
  const mountedRef = useRef(true);

  const addLog = useCallback((msg: string, type?: LogEntry['type']) => {
    setSystemLogs((prev) => {
      const next = [...prev, { timestamp: formatLogTimestamp(), message: msg, type }];
      return next.length > 200 ? next.slice(-200) : next;
    });
  }, []);

  useEffect(() => {
    mountedRef.current = true;
    if (!reportId) return;

    const load = async () => {
      addLog('Loading interaction data...');
      try {
        const reportRes = await getReport(reportId);
        if (reportRes.success) {
          const simId = reportRes.data.simulation_id;
          if (simId) {
            setSimulationId(simId);
            const simRes = await getSimulation(simId);
            if (simRes.success) {
              const projectId = simRes.data.project_id;
              if (projectId) {
                const projRes = await getProject(projectId);
                if (projRes.success) {
                  const graphId = projRes.data.graph_id;
                  if (graphId) {
                    setGraphLoading(true);
                    const gRes = await getGraphData(graphId);
                    if (gRes.success && mountedRef.current) setGraphData(gRes.data as typeof graphData);
                    setGraphLoading(false);
                  }
                }
              }
            }
          }
        }
      } catch (e) {
        addLog(`Error: ${(e as Error).message}`, 'error');
      }
    };
    load();

    return () => { mountedRef.current = false; };
  }, [reportId, addLog]);

  const leftPanelStyle = viewMode === 'graph' ? { width: '100%', opacity: 1 } : viewMode === 'workbench' ? { width: '0%', opacity: 0 } : { width: '50%', opacity: 1 };
  const rightPanelStyle = viewMode === 'workbench' ? { width: '100%', opacity: 1 } : viewMode === 'graph' ? { width: '0%', opacity: 0 } : { width: '50%', opacity: 1 };

  return (
    <div className="flex h-screen flex-col">
      <header className="flex h-[60px] items-center justify-between border-b border-brand-100 bg-white px-4">
        <button onClick={() => navigate('/')} className="flex items-center gap-2 hover:opacity-80"><img src="/assets/nclouds-icon.svg" alt="nClouds" className="h-6 w-6" /><span className="text-lg font-bold text-brand-950">nVision</span></button>
        <div className="flex items-center gap-1 rounded-lg bg-brand-50 p-0.5">
          {(['graph', 'split', 'workbench'] as ViewMode[]).map((mode) => (
            <button key={mode} onClick={() => setViewMode(mode)}
              className={cx('rounded-md px-3 py-1 text-xs font-medium capitalize', viewMode === mode ? 'bg-white text-brand-900 shadow-sm' : 'text-brand-500')}>
              {mode}
            </button>
          ))}
        </div>
        <div className="flex items-center gap-1.5">
          <span className="text-xs text-brand-500">Step 5/5 · Interaction</span>
          <span className={cx('h-2 w-2 rounded-full', currentStatus === 'ready' ? 'bg-green-500' : 'bg-brand-500')} />
        </div>
      </header>

      <div className="flex flex-1 overflow-hidden">
        <div className="h-full overflow-hidden transition-all duration-500" style={leftPanelStyle}>
          <GraphPanel graphData={graphData} loading={graphLoading} currentPhase={5}
            onToggleMaximize={() => setViewMode(viewMode === 'graph' ? 'split' : 'graph')} />
        </div>
        <div className="h-full overflow-hidden transition-all duration-500" style={rightPanelStyle}>
          <Step5Interaction
            reportId={reportId || ''}
            simulationId={simulationId}
            systemLogs={systemLogs}
            onAddLog={addLog}
            onUpdateStatus={setCurrentStatus}
          />
        </div>
      </div>
    </div>
  );
}

// frontend/src/views/InteractionView.vue
<template>
  <div class="main-view">
    <!-- Header -->
    <header class="app-header">
      <div class="header-left">
        <div class="brand" @click="router.push('/')">MIROFISH</div>
      </div>
      
      <div class="header-center">
        <div class="view-switcher">
          <button 
            v-for="mode in ['graph', 'split', 'workbench']" 
            :key="mode"
            class="switch-btn"
            :class="{ active: viewMode === mode }"
            @click="viewMode = mode"
          >
            {{ { graph: 'Graph', split: 'Split', workbench: 'Workbench' }[mode] }}
          </button>
        </div>
      </div>

      <div class="header-right">
        <div class="workflow-step">
          <span class="step-num">Step 5/5</span>
          <span class="step-name">Deep Interaction</span>
        </div>
        <div class="step-divider"></div>
        <span class="status-indicator" :class="statusClass">
          <span class="dot"></span>
          {{ statusText }}
        </span>
      </div>
    </header>

    <!-- Main Content Area -->
    <main class="content-area">
      <!-- Left Panel: Graph -->
      <div class="panel-wrapper left" :style="leftPanelStyle">
        <GraphPanel 
          :graphData="graphData"
          :loading="graphLoading"
          :currentPhase="5"
          :isSimulating="false"
          @refresh="refreshGraph"
          @toggle-maximize="toggleMaximize('graph')"
        />
      </div>

      <!-- Right Panel: Step5 Deep Interaction -->
      <div class="panel-wrapper right" :style="rightPanelStyle">
        <Step5Interaction
          :reportId="currentReportId"
          :simulationId="simulationId"
          :systemLogs="systemLogs"
          @add-log="addLog"
          @update-status="updateStatus"
        />
      </div>
    </main>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import GraphPanel from '../components/GraphPanel.vue'
import Step5Interaction from '../components/Step5Interaction.vue'
import { getProject, getGraphData } from '../api/graph'
import { getSimulation } from '../api/simulation'
import { getReport } from '../api/report'

const route = useRoute()
const router = useRouter()

// Props
const props = defineProps({
  reportId: String
})

// Layout State - default to workbench view
const viewMode = ref('workbench')

// Data State
const currentReportId = ref(route.params.reportId)
const simulationId = ref(null)
const projectData = ref(null)
const graphData = ref(null)
const graphLoading = ref(false)
const systemLogs = ref([])
const currentStatus = ref('ready') // ready | processing | completed | error

// --- Computed Layout Styles ---
const leftPanelStyle = computed(() => {
  if (viewMode.value === 'graph') return { width: '100%', opacity: 1, transform: 'translateX(0)' }
  if (viewMode.value === 'workbench') return { width: '0%', opacity: 0, transform: 'translateX(-20px)' }
  return { width: '50%', opacity: 1, transform: 'translateX(0)' }
})

const rightPanelStyle = computed(() => {
  if (viewMode.value === 'workbench') return { width: '100%', opacity: 1, transform: 'translateX(0)' }
  if (viewMode.value === 'graph') return { width: '0%', opacity: 0, transform: 'translateX(20px)' }
  return { width: '50%', opacity: 1, transform: 'translateX(0)' }
})

// --- Status Computed ---
const statusClass = computed(() => {
  return currentStatus.value
})

const statusText = computed(() => {
  if (currentStatus.value === 'error') return 'Error'
  if (currentStatus.value === 'completed') return 'Completed'
  if (currentStatus.value === 'processing') return 'Processing'
  return 'Ready'
})

// --- Helpers ---
const addLog = (msg) => {
  const time = new Date().toLocaleTimeString('en-US', { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' }) + '.' + new Date().getMilliseconds().toString().padStart(3, '0')
  systemLogs.value.push({ time, msg })
  if (systemLogs.value.length > 200) {
    systemLogs.value.shift()
  }
}

const updateStatus = (status) => {
  currentStatus.value = status
}

// --- Layout Methods ---
const toggleMaximize = (target) => {
  if (viewMode.value === target) {
    viewMode.value = 'split'
  } else {
    viewMode.value = target
  }
}

// --- Data Logic ---
const loadReportData = async () => {
  try {
    addLog(`Loading report data: ${currentReportId.value}`)
    
    // Get report info to obtain simulation_id
    const reportRes = await getReport(currentReportId.value)
    if (reportRes.success && reportRes.data) {
      const reportData = reportRes.data
      simulationId.value = reportData.simulation_id
      
      if (simulationId.value) {
        // Get simulation info
        const simRes = await getSimulation(simulationId.value)
        if (simRes.success && simRes.data) {
          const simData = simRes.data
          
          // Get project info
          if (simData.project_id) {
            const projRes = await getProject(simData.project_id)
            if (projRes.success && projRes.data) {
              projectData.value = projRes.data
              addLog(`Project loaded: ${projRes.data.project_id}`)
              
              // Get graph data
              if (projRes.data.graph_id) {
                await loadGraph(projRes.data.graph_id)
              }
            }
          }
        }
      }
    } else {
      addLog(`Failed to get report info: ${reportRes.error || 'Unknown error'}`)
    }
  } catch (err) {
    addLog(`Loading error: ${err.message}`)
  }
}

const loadGraph = async (graphId) => {
  graphLoading.value = true
  
  try {
    const res = await getGraphData(graphId)
    if (res.success) {
      graphData.value = res.data
      addLog('Graph data loaded successfully')
    }
  } catch (err) {
    addLog(`Failed to load graph: ${err.message}`)
  } finally {
    graphLoading.value = false
  }
}

const refreshGraph = () => {
  if (projectData.value?.graph_id) {
    loadGraph(projectData.value.graph_id)
  }
}

// Watch route params
watch(() => route.params.reportId, (newId) => {
  if (newId && newId !== currentReportId.value) {
    currentReportId.value = newId
    loadReportData()
  }
}, { immediate: true })

onMounted(() => {
  addLog('InteractionView initialized')
  loadReportData()
})
</script>

<style scoped>
.main-view {
  height: 100vh;
  display: flex;
  flex-direction: column;
  background: #FFF;
  overflow: hidden;
  font-family: 'Space Grotesk', 'Noto Sans SC', system-ui, sans-serif;
}

/* Header */
.app-header {
  height: 60px;
  border-bottom: 1px solid #EAEAEA;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 24px;
  background: #FFF;
  z-index: 100;
  position: relative;
}

.header-center {
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
}

.brand {
  font-family: 'JetBrains Mono', monospace;
  font-weight: 800;
  font-size: 18px;
  letter-spacing: 1px;
  cursor: pointer;
}

.view-switcher {
  display: flex;
  background: #F5F5F5;
  padding: 4px;
  border-radius: 6px;
  gap: 4px;
}

.switch-btn {
  border: none;
  background: transparent;
  padding: 6px 16px;
  font-size: 12px;
  font-weight: 600;
  color: #666;
  border-radius: 4px;
  cursor: pointer;
  transition: all 0.2s;
}

.switch-btn.active {
  background: #FFF;
  color: #000;
  box-shadow: 0 2px 4px rgba(0,0,0,0.05);
}

.header-right {
  display: flex;
  align-items: center;
  gap: 16px;
}

.workflow-step {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
}

.step-num {
  font-family: 'JetBrains Mono', monospace;
  font-weight: 700;
  color: #999;
}

.step-name {
  font-weight: 700;
  color: #000;
}

.step-divider {
  width: 1px;
  height: 14px;
  background-color: #E0E0E0;
}

.status-indicator {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  color: #666;
  font-weight: 500;
}

.dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #CCC;
}

.status-indicator.ready .dot { background: #4CAF50; }
.status-indicator.processing .dot { background: #FF9800; animation: pulse 1s infinite; }
.status-indicator.completed .dot { background: #4CAF50; }
.status-indicator.error .dot { background: #F44336; }

@keyframes pulse { 50% { opacity: 0.5; } }

/* Content */
.content-area {
  flex: 1;
  display: flex;
  position: relative;
  overflow: hidden;
}

.panel-wrapper {
  height: 100%;
  overflow: hidden;
  transition: width 0.4s cubic-bezier(0.25, 0.8, 0.25, 1), opacity 0.3s ease, transform 0.3s ease;
  will-change: width, opacity, transform;
}

.panel-wrapper.left {
  border-right: 1px solid #EAEAEA;
}
</style>
