// frontend-react/src/pages/simulation-view.tsx
import { useState, useEffect, useCallback, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getSimulation, closeSimulationEnv, stopSimulation, getEnvStatus } from '../api/simulation';
import { getProject, getGraphData } from '../api/graph';
import { GraphPanel } from '../components/graph-panel/graph-panel';
import { Step2EnvSetup } from '../components/wizard/step-2-env-setup';
import { formatLogTimestamp, type LogEntry } from '../components/shared/log-viewer';
import type { GraphNode, GraphEdge, Project } from '../api/types';
import { cx } from '../utils/cx';

type ViewMode = 'graph' | 'split' | 'workbench';

export function SimulationView() {
  const { simulationId } = useParams<{ simulationId: string }>();
  const navigate = useNavigate();

  const [viewMode, setViewMode] = useState<ViewMode>('split');
  const [graphData, setGraphData] = useState<{ nodes: GraphNode[]; edges: GraphEdge[]; node_count: number; edge_count: number } | null>(null);
  const [graphLoading, setGraphLoading] = useState(false);
  const [projectData, setProjectData] = useState<Project | null>(null);
  const [systemLogs, setSystemLogs] = useState<LogEntry[]>([]);
  const [currentStatus, setCurrentStatus] = useState('processing');
  const mountedRef = useRef(true);

  const addLog = useCallback((msg: string, type?: LogEntry['type']) => {
    setSystemLogs((prev) => {
      const next = [...prev, { timestamp: formatLogTimestamp(), message: msg, type }];
      return next.length > 100 ? next.slice(-100) : next;
    });
  }, []);

  const loadGraph = useCallback(async (graphId: string) => {
    setGraphLoading(true);
    try {
      const res = await getGraphData(graphId);
      if (res.success && mountedRef.current) {
        setGraphData(res.data as typeof graphData);
        addLog('Graph loaded.', 'success');
      }
    } catch { /* ignore */ }
    finally { setGraphLoading(false); }
  }, [addLog]);

  useEffect(() => {
    mountedRef.current = true;
    if (!simulationId) return;

    const load = async () => {
      addLog('Loading simulation data...');
      try {
        // Check and stop any running simulation
        try {
          const envRes = await getEnvStatus({ simulation_id: simulationId });
          if (envRes.success && (envRes.data as { status?: string }).status === 'running') {
            addLog('Closing running environment...');
            await closeSimulationEnv({ simulation_id: simulationId, timeout: 10 });
          }
        } catch { /* ignore */ }

        const simRes = await getSimulation(simulationId);
        if (simRes.success && mountedRef.current) {
          const projectId = simRes.data.project_id;
          if (projectId) {
            const projRes = await getProject(projectId);
            if (projRes.success && mountedRef.current) {
              setProjectData(projRes.data);
              const graphId = projRes.data.graph_id;
              if (graphId) await loadGraph(graphId);
            }
          }
        }
      } catch (e) {
        addLog(`Error: ${(e as Error).message}`, 'error');
      }
    };
    load();

    return () => { mountedRef.current = false; };
  }, [simulationId, addLog, loadGraph]);

  const handleNextStep = (params?: { maxRounds?: number }) => {
    const url = `/simulation/${simulationId}/start${params?.maxRounds ? `?maxRounds=${params.maxRounds}` : ''}`;
    navigate(url);
  };

  const handleGoBack = () => {
    if (projectData?.project_id) {
      navigate(`/process/${projectData.project_id}`);
    } else {
      navigate('/');
    }
  };

  const leftPanelStyle = viewMode === 'graph' ? { width: '100%', opacity: 1 } : viewMode === 'workbench' ? { width: '0%', opacity: 0 } : { width: '50%', opacity: 1 };
  const rightPanelStyle = viewMode === 'workbench' ? { width: '100%', opacity: 1 } : viewMode === 'graph' ? { width: '0%', opacity: 0 } : { width: '50%', opacity: 1 };

  return (
    <div className="flex h-screen flex-col">
      <header className="flex h-[60px] items-center justify-between border-b border-brand-100 bg-white px-4">
        <button onClick={() => navigate('/')} className="flex items-center gap-2 hover:opacity-80"><img src="/assets/nclouds-icon.svg" alt="nClouds" className="h-6 w-6" /><span className="text-lg font-bold text-brand-950">nVision</span></button>
        <div className="flex items-center gap-1 rounded-lg bg-brand-50 p-0.5">
          {(['graph', 'split', 'workbench'] as ViewMode[]).map((mode) => (
            <button key={mode} onClick={() => setViewMode(mode)}
              className={cx('rounded-md px-3 py-1 text-xs font-medium capitalize', viewMode === mode ? 'bg-white text-brand-900 shadow-sm' : 'text-brand-500')}>
              {mode}
            </button>
          ))}
        </div>
        <div className="flex items-center gap-1.5">
          <span className="text-xs text-brand-500">Step 2/5 · Environment Setup</span>
          <span className={cx('h-2 w-2 rounded-full', currentStatus === 'completed' ? 'bg-green-500' : 'bg-brand-500')} />
        </div>
      </header>

      <div className="flex flex-1 overflow-hidden">
        <div className="h-full overflow-hidden transition-all duration-500" style={leftPanelStyle}>
          <GraphPanel graphData={graphData} loading={graphLoading} currentPhase={2}
            onRefresh={() => { if (projectData?.graph_id) loadGraph(projectData.graph_id as string); }}
            onToggleMaximize={() => setViewMode(viewMode === 'graph' ? 'split' : 'graph')} />
        </div>
        <div className="h-full overflow-hidden transition-all duration-500" style={rightPanelStyle}>
          <Step2EnvSetup
            simulationId={simulationId || ''}
            projectData={projectData}
            graphData={graphData}
            systemLogs={systemLogs}
            onGoBack={handleGoBack}
            onNextStep={handleNextStep}
            onAddLog={addLog}
            onUpdateStatus={setCurrentStatus}
          />
        </div>
      </div>
    </div>
  );
}

// frontend/src/views/SimulationView.vue
<template>
  <div class="main-view">
    <!-- Header -->
    <header class="app-header">
      <div class="header-left">
        <div class="brand" @click="router.push('/')">MIROFISH</div>
      </div>
      
      <div class="header-center">
        <div class="view-switcher">
          <button 
            v-for="mode in ['graph', 'split', 'workbench']" 
            :key="mode"
            class="switch-btn"
            :class="{ active: viewMode === mode }"
            @click="viewMode = mode"
          >
            {{ { graph: 'Graph', split: 'Split', workbench: 'Workbench' }[mode] }}
          </button>
        </div>
      </div>

      <div class="header-right">
        <div class="workflow-step">
          <span class="step-num">Step 2/5</span>
          <span class="step-name">Environment Setup</span>
        </div>
        <div class="step-divider"></div>
        <span class="status-indicator" :class="statusClass">
          <span class="dot"></span>
          {{ statusText }}
        </span>
      </div>
    </header>

    <!-- Main Content Area -->
    <main class="content-area">
      <!-- Left Panel: Graph -->
      <div class="panel-wrapper left" :style="leftPanelStyle">
        <GraphPanel 
          :graphData="graphData"
          :loading="graphLoading"
          :currentPhase="2"
          @refresh="refreshGraph"
          @toggle-maximize="toggleMaximize('graph')"
        />
      </div>

      <!-- Right Panel: Step2 Environment Setup -->
      <div class="panel-wrapper right" :style="rightPanelStyle">
        <Step2EnvSetup
          :simulationId="currentSimulationId"
          :projectData="projectData"
          :graphData="graphData"
          :systemLogs="systemLogs"
          @go-back="handleGoBack"
          @next-step="handleNextStep"
          @add-log="addLog"
          @update-status="updateStatus"
        />
      </div>
    </main>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import GraphPanel from '../components/GraphPanel.vue'
import Step2EnvSetup from '../components/Step2EnvSetup.vue'
import { getProject, getGraphData } from '../api/graph'
import { getSimulation, stopSimulation, getEnvStatus, closeSimulationEnv } from '../api/simulation'

const route = useRoute()
const router = useRouter()

// Props
const props = defineProps({
  simulationId: String
})

// Layout State
const viewMode = ref('split')

// Data State
const currentSimulationId = ref(route.params.simulationId)
const projectData = ref(null)
const graphData = ref(null)
const graphLoading = ref(false)
const systemLogs = ref([])
const currentStatus = ref('processing') // processing | completed | error

// --- Computed Layout Styles ---
const leftPanelStyle = computed(() => {
  if (viewMode.value === 'graph') return { width: '100%', opacity: 1, transform: 'translateX(0)' }
  if (viewMode.value === 'workbench') return { width: '0%', opacity: 0, transform: 'translateX(-20px)' }
  return { width: '50%', opacity: 1, transform: 'translateX(0)' }
})

const rightPanelStyle = computed(() => {
  if (viewMode.value === 'workbench') return { width: '100%', opacity: 1, transform: 'translateX(0)' }
  if (viewMode.value === 'graph') return { width: '0%', opacity: 0, transform: 'translateX(20px)' }
  return { width: '50%', opacity: 1, transform: 'translateX(0)' }
})

// --- Status Computed ---
const statusClass = computed(() => {
  return currentStatus.value
})

const statusText = computed(() => {
  if (currentStatus.value === 'error') return 'Error'
  if (currentStatus.value === 'completed') return 'Ready'
  return 'Preparing'
})

// --- Helpers ---
const addLog = (msg) => {
  const time = new Date().toLocaleTimeString('en-US', { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' }) + '.' + new Date().getMilliseconds().toString().padStart(3, '0')
  systemLogs.value.push({ time, msg })
  if (systemLogs.value.length > 100) {
    systemLogs.value.shift()
  }
}

const updateStatus = (status) => {
  currentStatus.value = status
}

// --- Layout Methods ---
const toggleMaximize = (target) => {
  if (viewMode.value === target) {
    viewMode.value = 'split'
  } else {
    viewMode.value = target
  }
}

const handleGoBack = () => {
  // Return to the process page
  if (projectData.value?.project_id) {
    router.push({ name: 'Process', params: { projectId: projectData.value.project_id } })
  } else {
    router.push('/')
  }
}

const handleNextStep = (params = {}) => {
  addLog('Entering Step 3: Start Simulation')
  
  // Log simulation round config
  if (params.maxRounds) {
    addLog(`Custom simulation rounds: ${params.maxRounds}`)
  } else {
    addLog('Using auto-configured simulation rounds')
  }
  
  // Build route params
  const routeParams = {
    name: 'SimulationRun',
    params: { simulationId: currentSimulationId.value }
  }
  
  // If custom rounds are set, pass via query params
  if (params.maxRounds) {
    routeParams.query = { maxRounds: params.maxRounds }
  }
  
  // Navigate to Step 3 page
  router.push(routeParams)
}

// --- Data Logic ---

/**
 * Check and stop any running simulation
 * When the user returns from Step 3 to Step 2, assume they want to exit the simulation
 */
const checkAndStopRunningSimulation = async () => {
  if (!currentSimulationId.value) return
  
  try {
    // First check if the simulation environment is alive
    const envStatusRes = await getEnvStatus({ simulation_id: currentSimulationId.value })
    
    if (envStatusRes.success && envStatusRes.data?.env_alive) {
      addLog('Detected running simulation environment, closing...')
      
      // Try to gracefully close the simulation environment
      try {
        const closeRes = await closeSimulationEnv({ 
          simulation_id: currentSimulationId.value,
          timeout: 10  // 10-second timeout
        })
        
        if (closeRes.success) {
          addLog('✓ Simulation environment closed')
        } else {
          addLog(`Failed to close environment: ${closeRes.error || 'Unknown error'}`)
          // If graceful close fails, attempt force stop
          await forceStopSimulation()
        }
      } catch (closeErr) {
        addLog(`Environment close error: ${closeErr.message}`)
        // If graceful close throws an error, attempt force stop
        await forceStopSimulation()
      }
    } else {
      // Environment not running, but process may still exist; check simulation status
      const simRes = await getSimulation(currentSimulationId.value)
      if (simRes.success && simRes.data?.status === 'running') {
        addLog('Detected simulation status as running, stopping...')
        await forceStopSimulation()
      }
    }
  } catch (err) {
    // Failure to check environment status does not block subsequent flow
    console.warn('Failed to check simulation status:', err)
  }
}

/**
 * Force stop simulation
 */
const forceStopSimulation = async () => {
  try {
    const stopRes = await stopSimulation({ simulation_id: currentSimulationId.value })
    if (stopRes.success) {
      addLog('✓ Simulation force stopped')
    } else {
      addLog(`Force stop failed: ${stopRes.error || 'Unknown error'}`)
    }
  } catch (err) {
    addLog(`Force stop error: ${err.message}`)
  }
}

const loadSimulationData = async () => {
  try {
    addLog(`Loading simulation data: ${currentSimulationId.value}`)
    
    // Get simulation info
    const simRes = await getSimulation(currentSimulationId.value)
    if (simRes.success && simRes.data) {
      const simData = simRes.data
      
      // Get project info
      if (simData.project_id) {
        const projRes = await getProject(simData.project_id)
        if (projRes.success && projRes.data) {
          projectData.value = projRes.data
          addLog(`Project loaded: ${projRes.data.project_id}`)
          
          // Get graph data
          if (projRes.data.graph_id) {
            await loadGraph(projRes.data.graph_id)
          }
        }
      }
    } else {
      addLog(`Failed to load simulation data: ${simRes.error || 'Unknown error'}`)
    }
  } catch (err) {
    addLog(`Loading error: ${err.message}`)
  }
}

const loadGraph = async (graphId) => {
  graphLoading.value = true
  try {
    const res = await getGraphData(graphId)
    if (res.success) {
      graphData.value = res.data
      addLog('Graph data loaded successfully')
    }
  } catch (err) {
    addLog(`Failed to load graph: ${err.message}`)
  } finally {
    graphLoading.value = false
  }
}

const refreshGraph = () => {
  if (projectData.value?.graph_id) {
    loadGraph(projectData.value.graph_id)
  }
}

onMounted(async () => {
  addLog('SimulationView initialized')
  
  // Check and stop any running simulation (when user returns from Step 3)
  await checkAndStopRunningSimulation()
  
  // Load simulation data
  loadSimulationData()
})
</script>

<style scoped>
.main-view {
  height: 100vh;
  display: flex;
  flex-direction: column;
  background: #FFF;
  overflow: hidden;
  font-family: 'Space Grotesk', 'Noto Sans SC', system-ui, sans-serif;
}

/* Header */
.app-header {
  height: 60px;
  border-bottom: 1px solid #EAEAEA;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 24px;
  background: #FFF;
  z-index: 100;
  position: relative;
}

.brand {
  font-family: 'JetBrains Mono', monospace;
  font-weight: 800;
  font-size: 18px;
  letter-spacing: 1px;
  cursor: pointer;
}

.header-center {
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
}

.view-switcher {
  display: flex;
  background: #F5F5F5;
  padding: 4px;
  border-radius: 6px;
  gap: 4px;
}

.switch-btn {
  border: none;
  background: transparent;
  padding: 6px 16px;
  font-size: 12px;
  font-weight: 600;
  color: #666;
  border-radius: 4px;
  cursor: pointer;
  transition: all 0.2s;
}

.switch-btn.active {
  background: #FFF;
  color: #000;
  box-shadow: 0 2px 4px rgba(0,0,0,0.05);
}

.header-right {
  display: flex;
  align-items: center;
  gap: 16px;
}

.workflow-step {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
}

.step-num {
  font-family: 'JetBrains Mono', monospace;
  font-weight: 700;
  color: #999;
}

.step-name {
  font-weight: 700;
  color: #000;
}

.step-divider {
  width: 1px;
  height: 14px;
  background-color: #E0E0E0;
}

.status-indicator {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  color: #666;
  font-weight: 500;
}

.dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #CCC;
}

.status-indicator.processing .dot { background: #FF5722; animation: pulse 1s infinite; }
.status-indicator.completed .dot { background: #4CAF50; }
.status-indicator.error .dot { background: #F44336; }

@keyframes pulse { 50% { opacity: 0.5; } }

/* Content */
.content-area {
  flex: 1;
  display: flex;
  position: relative;
  overflow: hidden;
}

.panel-wrapper {
  height: 100%;
  overflow: hidden;
  transition: width 0.4s cubic-bezier(0.25, 0.8, 0.25, 1), opacity 0.3s ease, transform 0.3s ease;
  will-change: width, opacity, transform;
}

.panel-wrapper.left {
  border-right: 1px solid #EAEAEA;
}
</style>
